AWSTemplateFormatVersion: 2010-09-09

Description:
  Kinesis Firehose
  FirehoseStreamにPutRecordすると、その内容がS3バケットに格納される。

Resources:
  Stream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

  Firehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    DependsOn: DeliveryPolicy
    Properties:
      DeliveryStreamType: KinesisStreamAsSource
      KinesisStreamSourceConfiguration:
        KinesisStreamARN: !GetAtt Stream.Arn
        RoleARN: !GetAtt DeliveryRole.Arn
      S3DestinationConfiguration:
        BucketARN: !GetAtt S3Bucket.Arn
        BufferingHints:
          IntervalInSeconds: 60
        CloudWatchLoggingOptions:
          # エラーをログする。正常時は何も出力されない。
          # S3アクセスが許可されていない場合に出力された。
          Enabled: True
          LogGroupName: !Ref LogGroup
          LogStreamName: !Ref LogStream
        CompressionFormat: GZIP
        ErrorOutputPrefix: err/
        RoleARN: !GetAtt DeliveryRole.Arn

  S3Bucket:
    Type: AWS::S3::Bucket

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/kinesisfirehose/practice-firehose
      RetentionInDays: 1

  # Firehoseは作成しない様子。作成する必要がある。
  LogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref LogGroup
      LogStreamName: S3Delivery

  DeliveryRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref 'AWS::AccountId'

  DeliveryPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: firehose_delivery_policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
            Resource:
              - !Sub "${S3Bucket.Arn}"
              - !Sub "${S3Bucket.Arn}/*"
          - Effect: Allow
            Action:
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
              - kinesis:DescribeStream
              - kinesis:GetShardIterator
              - kinesis:GetRecords
              - kinesis:ListShards
            Resource:
              - !GetAtt Stream.Arn
      Roles:
        - !Ref DeliveryRole

Outputs:
  StreamName:
    Value: !Ref Stream
